// react_user/src/views/book/ReadingHistory.tsx
import { useEffect, useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button, Image, Tag } from 'antd';
import { CloseOutlined, UserOutlined, HistoryOutlined } from '@ant-design/icons';
import { useReadingHistoryStore, useBookShelfStore } from '@/store';

export default function ReadingHistory() {
  const navigate = useNavigate();
  const historyStore = useReadingHistoryStore();
  const shelfStore = useBookShelfStore();
  const [showClose, setShowClose] = useState(false);
  const [isLessThan768, setIsLessThan768] = useState(window.innerWidth < 768);

  const width = 96;
  const height = 144;

  const shelfIds = useMemo(
    () => shelfStore.bookShelf.map((item) => item.id),
    [shelfStore.bookShelf],
  );

  useEffect(() => {
    const handler = () => setIsLessThan768(window.innerWidth < 768);
    window.addEventListener('resize', handler);
    return () => window.removeEventListener('resize', handler);
  }, []);

  useEffect(() => {
    historyStore.get();
  }, []);

  return (
    <div>
      {!isLessThan768 && (
        <div style={{ padding: '0.5rem' }}>
          <Button onClick={() => setShowClose(!showClose)}>
            批量管理
          </Button>
        </div>
      )}

      <div
        style={{
          width: '100%',
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
          gap: '0.5rem',
          padding: '0.25rem',
        }}
      >
        {historyStore.getReadingHistory().map((item) => (
          <div
            key={item.id}
            className="bg-card"
            style={{
              display: 'flex',
              gap: '0.5rem',
              padding: '0.5rem',
              borderRadius: '0.5rem',
              position: 'relative',
            }}
          >
            {/* Close button for desktop batch mode */}
            {showClose && !isLessThan768 && (
              <div
                className="inner-close"
                onClick={() => historyStore.delete(item.id)}
                style={{ cursor: 'pointer' }}
              >
                <CloseOutlined />
              </div>
            )}

            <Image
              src={item.cover}
              height={height}
              width={width}
              preview={false}
              fallback="/figure.webp"
              style={{ objectFit: 'cover' }}
            />

            <div
              style={{
                flex: 1,
                display: 'flex',
                flexDirection: 'column',
                gap: '0.25rem',
              }}
            >
              <h5 style={{ margin: 0 }}>{item.name}</h5>

              <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                <UserOutlined style={{ fontSize: '14px' }} />
                <span style={{ fontSize: '0.8rem' }}>{item.author}</span>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                <HistoryOutlined style={{ fontSize: '14px' }} />
                <span style={{ fontSize: '0.8rem' }}>
                  上次阅读: {item.lastReadAt?.split('T')[0]}
                </span>
              </div>

              <div style={{ display: 'flex', gap: '0.5rem' }}>
                <Button
                  type="primary"
                  size="small"
                  onClick={() =>
                    navigate(
                      `/book-read/${item.id}/${item.lastChapterId}`,
                    )
                  }
                >
                  继续阅读
                </Button>
                {!shelfIds.includes(item.id) && (
                  <Button
                    size="small"
                    onClick={() => shelfStore.add(item.id)}
                  >
                    加入书架
                  </Button>
                )}
              </div>

              {/* Mobile delete */}
              {isLessThan768 && (
                <div
                  className="delete-768"
                  onClick={() => historyStore.delete(item.id)}
                  style={{
                    padding: '0.5rem',
                    textAlign: 'center',
                    borderRadius: '0.3rem',
                    cursor: 'pointer',
                  }}
                >
                  删除
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// user/src/views/book/ReadingHistory.vue
<template>
  <div>
    <div class="container hidden-768">
      <q-form-button @click="showClose = !showClose"> 批量管理 </q-form-button>
    </div>
    <div class="reading-history-container">
      <QSwiperAction
        v-for="histortItem in historyStore.getReadingHistory"
        :key="histortItem.id"
        :disabled="!isLessThan768"
        :threshold="30"
      >
        <template #default>
          <div class="bg-card container">
            <div
              v-show="showClose && !isLessThan768"
              class="inner-close"
              @click="historyStore.delete(histortItem.id)"
            >
              <q-icon icon="Close" size="16px" />
            </div>
            <QLazyImage
              :src="histortItem.cover"
              :height="height"
              :width="width"
            />
            <div class="container-flex-1 inner-container-column">
              <h5>
                {{ histortItem.name }}
              </h5>
              <div class="inner-container">
                <QIcon icon="User" size="14px" />
                <span class="text-08rem">{{ histortItem.author }}</span>
              </div>
              <div class="inner-container">
                <QIcon icon="History" size="14px" />
                <div class="inner-container">
                  <span class="text-08rem">上次阅读:</span>
                  <span class="text-08rem">{{
                    histortItem.last_read_at.split('T')[0]
                  }}</span>
                </div>
              </div>
              <div class="inner-container">
                <QFormButton
                  type="button"
                  @click="
                    router.push(
                      `/book-read/${histortItem.id}/${histortItem.last_chapter_id}`,
                    )
                  "
                >
                  继续阅读
                </QFormButton>
                <QFormButton
                  v-if="!shelfIds.includes(histortItem.id)"
                  type="button"
                  @click="shelfStore.add(histortItem.id)"
                >
                  加入书架
                </QFormButton>
              </div>
            </div>
          </div>
        </template>
        <template #action>
          <div
            class="container-center padding-46rem container-h100 delete-768"
            @click="historyStore.delete(histortItem.id)"
          >
            删除
          </div>
        </template>
      </QSwiperAction>
    </div>
  </div>
</template>
<script setup lang="ts">
import { computed, onBeforeMount, ref } from 'vue';
import router from '@/route';
import { useReadingHistoryStore } from '@/store';
import { useBookShelfStore } from '@/store';
import { useScreenSize } from 'qyani-components';
import {
  QSwiperAction,
  QLazyImage,
  QFormButton,
  QIcon,
} from 'qyani-components';
const width = ref(96);
const height = ref(144);
const isLessThan768 = useScreenSize.getWidth(768);
const showClose = ref(false);
const historyStore = useReadingHistoryStore();
const shelfStore = useBookShelfStore();
const shelfIds = computed(() => {
  return shelfStore.bookShelf.map((item) => item.id);
});
onBeforeMount(async () => {
  historyStore.get();
});
</script>
<style scoped lang="css">
.reading-history-container {
  width: 100%;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  grid-auto-rows: auto;
  gap: 0.5rem;
  padding: 0.25rem;
}
</style>
