// author/src/components/book/BookItem.vue
<template>
  <div class="container-column bg-card shadow-common">
    <div class="inner-container">
      <QLazyImage :src="book.cover" :height="80" :width="64" />
      <div class="inner-container-column container-flex-1">
        <h4 :title="book.name">
          {{
            book.name.length > 12
              ? book.name.substring(0, 12) + '...'
              : book.name
          }}
        </h4>
        <p class="container-space-between">
          <span class="litte-tag">{{
            book.is_ended ? '已完结' : '连载中'
          }}</span>
          <span class="text-muted text-08rem">{{ book.total_chapter }}章</span>
        </p>
      </div>
    </div>
    <p class="book-item-description text-description text-two-line">
      {{ book.description }}
    </p>
    <div class="container-space-between">
      <div
        class="container-align-center gap-fourth mouse-cursor text-primary"
        @click="
          router.push({
            name: 'BookInfoEdit',
            query: {
              id: book.id,
            },
          })
        "
      >
        <QIcon icon="Edit" size="16px" />
        <span class="text-08rem">编辑</span>
      </div>
      <div
        class="container-align-center gap-fourth mouse-cursor"
        @click="
          router.push({
            name: 'BookDetail',
            params: {
              id: book.id,
            },
          })
        "
      >
        <QIcon icon="EyeOpen" size="16px" />
        <span class="text-08rem text-muted">查看</span>
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import type { Book } from '@guga-reading/types';
import { QLazyImage, QIcon } from 'qyani-components';
import { router } from '@/route';
defineOptions({
  name: 'BookItem',
});
defineProps<{
  book: Book;
}>();
</script>
<style scoped></style>

// react_user/src/components/BookItem.tsx
import { useNavigate } from 'react-router-dom';
import type { Book } from '@guga-reading/types';
import { Image } from 'antd';

interface BookItemProps {
  book: Book;
  width: number;
  height: number;
}

export default function BookItem({ book, width, height }: BookItemProps) {
  const navigate = useNavigate();

  return (
    <div
      className="inner-container mouse-cursor"
      onClick={() => navigate(`/book-detail/${book.id}`)}
      style={{ cursor: 'pointer' }}
    >
      <Image
        src={book.cover}
        width={width}
        height={height}
        preview={false}
        fallback="/figure.webp"
        style={{ objectFit: 'cover' }}
      />
      <div
        className="container-flex-1 inner-container-column container-h100 overflow-hidden"
        style={{ marginLeft: '0.5rem' }}
      >
        <h4>{book.name}</h4>
        <h6 style={{ color: '#888' }}>作者: {book.author}</h6>
        <p
          className="inner-container-column container-flex-1 text-muted text-08rem text-overflow"
          style={{
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            fontSize: '0.8rem',
            color: '#999',
          }}
        >
          {book.description}
        </p>
      </div>
    </div>
  );
}
