// react_user/src/views/Home.tsx
import { useEffect, useRef, useState } from 'react';
import { Skeleton } from 'antd';
import { useBookStore } from '@/store';
import BookItem from '@/components/BookItem';

export default function Home() {
  const bookStore = useBookStore();
  const [selectedCategory, setSelectedCategory] = useState(
    bookStore.currentCategory || '',
  );
  const scrollRef = useRef<HTMLDivElement>(null);
  const width = 90;
  const height = 120;

  useEffect(() => {
    bookStore.getBookCategory().then(() => {
      if (!selectedCategory && bookStore.categories.length > 0) {
        setSelectedCategory(bookStore.categories[0]);
      }
    });
  }, []);

  useEffect(() => {
    if (selectedCategory) {
      bookStore.setCurrentCategory(selectedCategory);
      bookStore.addBookByCategory();
    }
  }, [selectedCategory]);

  // Restore scroll position
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTo({ top: bookStore.scrollTo, behavior: 'instant' as ScrollBehavior });
    }
  }, []);

  const handleScroll = () => {
    if (scrollRef.current) {
      bookStore.setScrollTo(scrollRef.current.scrollTop);
      const { scrollTop, scrollHeight, clientHeight } = scrollRef.current;
      if (scrollHeight - scrollTop - clientHeight < 100) {
        bookStore.addBookByCategory();
      }
    }
  };

  const books = bookStore.getCategoryBook();

  return (
    <div
      className="container-column bg-card container-w100"
      style={{ width: '100%' }}
    >
      <div
        className="container-banner"
        style={{
          display: 'flex',
          gap: '0.5rem',
          padding: '0.5rem',
          overflowX: 'auto',
          margin: '0 auto',
          flexWrap: 'nowrap',
        }}
      >
        {bookStore.categories.map((value) => (
          <span
            key={value}
            onClick={() => setSelectedCategory(value)}
            style={{
              cursor: 'pointer',
              padding: '0.25rem 0.5rem',
              borderRadius: '0.3rem',
              whiteSpace: 'nowrap',
              background:
                selectedCategory === value
                  ? 'var(--primary-color, #6366f1)'
                  : undefined,
              color: selectedCategory === value ? '#fff' : undefined,
            }}
            className="bg-hover-secondary"
          >
            {value}
          </span>
        ))}
      </div>
      <div
        ref={scrollRef}
        onScroll={handleScroll}
        style={{
          height: 'calc(100vh - 6rem)',
          overflowY: 'auto',
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, 350px)',
          gridAutoRows: '120px',
          gap: '1rem',
          padding: '1rem',
          borderTop: '1px solid var(--primary-color, #6366f1)',
        }}
      >
        {books.map((book) => (
          <BookItem key={book.id} book={book} width={width} height={height} />
        ))}
        {bookStore.loading &&
          Array.from({ length: 25 }).map((_, i) => (
            <Skeleton key={i} active avatar paragraph={{ rows: 2 }} />
          ))}
      </div>
    </div>
  );
}

// user/src/views/Home.vue
<script setup lang="ts">
import { useBookStore } from '@/store';
import {
  onActivated,
  onBeforeMount,
  onMounted,
  ref,
  useTemplateRef,
  watch,
} from 'vue';
import BookItem from '@/components/BookItem.vue';
import { QScrollContainer } from 'qyani-components';

defineOptions({
  name: 'Home',
});
const bookStore = useBookStore();
const width = 90;
const height = 120;
const refScrollContainer =
  useTemplateRef<InstanceType<typeof QScrollContainer>>('home-container');
const selectedCategory = ref(bookStore.currentCategory ?? '');

watch(
  () => selectedCategory.value,
  (newValue) => {
    bookStore.setCurrentCategory(newValue);
    bookStore.addBookByCategory();
  },
);

onBeforeMount(async () => {
  bookStore.getBookCategory().then(() => {
    if (selectedCategory.value == '' && bookStore.categories.length > 0) {
      selectedCategory.value = bookStore.categories[0];
    }
  });
});
onMounted(() => {
  refScrollContainer.value?.scrollTo({
    top: bookStore.scrollTo,
    behavior: 'instant',
  });
});
onActivated(() => {
  refScrollContainer.value?.scrollTo({
    top: bookStore.scrollTo,
    behavior: 'instant',
  });
});
</script>

<template>
  <div class="container-column bg-card container-w100">
    <div class="container-banner scroll-container container margin-auto">
      <span
        v-for="value in bookStore.categories"
        :key="value"
        :class="[{ 'active-common': selectedCategory === value }]"
        @click="selectedCategory = value"
        class="text-nowrap padding-fourth-rem radius-third-rem bg-hover-secondary mouse-cursor"
      >
        {{ value }}
      </span>
    </div>
    <QScrollContainer
      ref="home-container"
      scroll-y
      class="scroll-container home-container"
      style="height: calc(100vh - 6rem)"
      @ended="bookStore.addBookByCategory()"
      @scroll="({ y }: { y: number }) => bookStore.setScrollTo(y)"
    >
      <BookItem
        v-for="book in bookStore.getCategoryBook"
        :key="book.id"
        :book="book"
        :width="width"
        :height="height"
      />
    </QScrollContainer>
  </div>
</template>
<style lang="css" scoped>
.home-container {
  display: grid;
  grid-template-columns: repeat(auto-fill, 350px);
  grid-auto-rows: 120px;
  gap: 1rem;
  padding: 1rem;
  border-top: 1px solid var(--primary-color);
}
</style>
