// user/src/views/book/BookRead.vue
<template>
  <div
    ref="bookReadContainer"
    class="container-w100 scroll-container"
    style="height: 100vh"
  >
    <div
      class="book-read-container"
      :style="{
        backgroundColor: useReadingSetting.readSettings.backgroundColor,
      }"
    >
      <QLoading
        v-show="loading"
        style="height: 100vh; width: 100%"
        type="skeleton"
      />
      <div
        v-show="!loading"
        class="book-read-content"
        :style="{
          fontSize: `${useReadingSetting.readSettings.fontSize}px`,
          fontFamily: useReadingSetting.readSettings.fontFamily,
          lineHeight: `${useReadingSetting.readSettings.lineHeight}px`,
          letterSpacing: `${useReadingSetting.readSettings.letterSpacing}px`,
          color: useReadingSetting.readSettings.color,
        }"
        @click="shwoBottomSettings = true"
        v-html="content"
      />
      <div class="book-read-sidebar bg-card hidden-768 container-column">
        <div
          class="inner-container-column container-align-center bg-hover-secondary"
          @click="
            currentContentIndex > 0
              ? run(computeCatalog[currentContentIndex - 1].id)
              : void 0
          "
        >
          <QIcon icon="Up" size="24px" />
          <span class="text-08rem">上一章</span>
        </div>
        <div
          class="inner-container-column container-align-center bg-hover-secondary"
          @click="
            currentContentIndex < computeCatalog.length - 1
              ? run(computeCatalog[currentContentIndex + 1].id)
              : void 0
          "
        >
          <QIcon icon="Down" size="24px" />
          <span class="text-08rem">下一章</span>
        </div>
        <div
          class="inner-container-column container-align-center bg-hover-secondary"
          @click="showCatalog = true"
        >
          <QIcon icon="Catalog" size="24px" />
          <span class="text-08rem">目录</span>
        </div>
        <div
          class="inner-container-column container-align-center bg-hover-secondary"
          @click="showReadSettings = true"
        >
          <QIcon icon="Setting" size="24px" />
          <span class="text-08rem">阅读设置</span>
        </div>
        <div
          class="inner-container-column container-align-center bg-hover-secondary"
          @click="router.push(`/book-detail/${book.id}`)"
        >
          <QIcon icon="Book" size="24px" />
          <span class="text-08rem">书籍详情</span>
        </div>
        <div
          class="inner-container-column container-align-center"
          @click="fullScreen"
        >
          <QIcon icon="FullScreen" size="24px" />
          <span class="text-08rem">全屏</span>
        </div>
      </div>
      <QDrawer
        v-model:visible="showCatalog"
        direction="left"
        :close-on-click-overlay="true"
        :overlay="false"
      >
        <div class="book-read-catalog-container">
          <h3 class="text-one-line">
            {{ book.name }}
          </h3>
          <p class="container-space-between">
            <span>目录</span>
            <span
              class="mouse-cursor container gap-half"
              @click="catalogAscOrder = !catalogAscOrder"
            >
              {{ catalogAscOrder ? '升序' : '降序' }}
              <QIcon
                icon="Switch"
                :style="{
                  transform: `rotateZ(90deg) rotateY(${catalogAscOrder ? 0 : 180}deg) `,
                }"
                size="16px"
              />
            </span>
          </p>
          <div class="book-read-catalog scroll-container">
            <p
              v-for="item in computeCatalog"
              :key="item.id"
              class="bg-hover-secondary padding-24rem mouse-cursor radius-third-rem"
              :class="[
                {
                  'active-common': item.id === currentContentId,
                },
              ]"
              @click="
                () => {
                  run(item.id);
                  showCatalog = false;
                }
              "
            >
              {{ item.title }}
            </p>
          </div>
        </div>
      </QDrawer>
      <QDrawer
        :visible="shwoBottomSettings && isCanShowBottomSettings"
        direction="bottom"
        :close-on-click-overlay="true"
        @close="shwoBottomSettings = false"
        :overlay="false"
      >
        <div
          class="container-space-between container-wrap padding-fourth-rem"
          @click="shwoBottomSettings = false"
        >
          <div
            class="inner-container-column container-align-center"
            @click="
              currentContentIndex > 0
                ? run(computeCatalog[currentContentIndex - 1].id)
                : void 0
            "
          >
            <QIcon icon="Up" size="24px" />
            <span class="text-08rem">上一章</span>
          </div>
          <div
            class="inner-container-column container-align-center"
            @click="
              currentContentIndex < computeCatalog.length - 1
                ? run(computeCatalog[currentContentIndex + 1].id)
                : void 0
            "
          >
            <QIcon icon="Down" size="24px" />
            <span class="text-08rem">下一章</span>
          </div>
          <div
            class="inner-container-column container-align-center"
            @click="showCatalog = true"
          >
            <QIcon icon="Catalog" size="24px" />
            <span class="text-08rem">目录</span>
          </div>
          <div
            class="inner-container-column container-align-center"
            @click="showReadSettings = true"
          >
            <QIcon icon="Setting" size="24px" />
            <span class="text-08rem">阅读设置</span>
          </div>
          <div
            class="inner-container-column container-align-center"
            @click="router.push(`/book-detail/${book.id}`)"
          >
            <QIcon icon="Book" size="24px" />
            <span class="text-08rem">书籍详情</span>
          </div>
          <div
            class="inner-container-column container-align-center"
            @click="fullScreen"
          >
            <QIcon icon="FullScreen" size="24px" />
            <span class="text-08rem">全屏</span>
          </div>
        </div>
      </QDrawer>
      <QDrawer
        v-model:visible="showReadSettings"
        direction="left"
        :close-on-click-overlay="true"
        :overlay="false"
        @close="showReadSettings = false"
      >
        <ReadSetting />
      </QDrawer>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  computed,
  nextTick,
  onBeforeMount,
  onBeforeUnmount,
  ref,
  useTemplateRef,
  watch,
} from 'vue';
import type { Book, Catalog } from '@guga-reading/types';
import { useBookStore, useReadSettingStore } from '@/store';
import router from '@/route';
import {
  applySpacingToHtml,
  indexToCN,
  isHtml,
  toggleFullScreen,
  useApiBooks,
  useTitle,
} from '@guga-reading/shares';
import { useScreenSize, useThrottle } from 'qyani-components';
import { useReadingHistoryStore } from '@/store';
import { QLoading, QIcon, QDrawer } from 'qyani-components';
import { useApiReport } from '@guga-reading/shares';
import ReadSetting from '@/components/ReadSetting.vue';
const fullScreen = toggleFullScreen();
// 用于切换时滚动到顶部
const bookReadContainer = useTemplateRef<HTMLDivElement>('bookReadContainer');
// 书籍信息
const book = ref<Book>({} as Book);
// 目录
const catalog = ref<Catalog[]>([] as Catalog[]);
// 书籍存储
const bookStore = useBookStore();
// 是否显示目录
const showCatalog = ref<boolean>(false);
// 当前内容
const content = ref<string>('');
// 目录呈现顺序
const catalogAscOrder = ref(true);
// 当前内容对应的章节ID
const currentContentId = ref<number>(-1);
// 当前内容在目录中的索引
const currentContentIndex = computed(() => {
  const index = catalog.value.findIndex(
    (item) => item.id === currentContentId.value,
  );
  return index;
});
// 监听当前内容索引,并更新标题
watch(
  () => currentContentIndex.value,
  (index) => {
    useTitle(catalog.value[index].title);
  },
);
// 是否显示底部设置
const shwoBottomSettings = ref<boolean>(false);
// 是否显示阅读设置
const showReadSettings = ref<boolean>(false);
// 是否可以显示底部设置
const isCanShowBottomSettings = useScreenSize.getWidth(768);
// 阅读历史存储
const readingHistoryStore = useReadingHistoryStore();
// 目录
const computeCatalog = computed(() => {
  if (catalogAscOrder.value) {
    return catalog.value;
  } else {
    return [...catalog.value].reverse();
  }
});
const useReadingSetting = useReadSettingStore();
const heartBeat = {
  interval: 10000,
  timer: -1,
  task: async function () {
    if (currentContentId.value !== -1) {
      useApiReport.reportChapterRead(
        book.value.id,
        currentContentId.value,
        'heartbeat',
      );
    }
  },
  start: function () {
    this.stop();
    this.timer = setInterval(heartBeat.task, heartBeat.interval);
  },
  stop: function () {
    clearInterval(this.timer);
    this.timer = -1;
  },
};
const updateReadingHistory = useThrottle(
  async (bookId: number, chapterId: number, index: number) => {
    readingHistoryStore.update(bookId, chapterId, index);
  },
);
const loading = ref<boolean>(false);
/**
 * 加载章节内容
 * @param chapterId 章节ID
 */
const run = async (chapterId: number) => {
  // 如果当前内容ID等于要加载的内容ID,则返回,避免重复加载
  if (currentContentId.value === chapterId) {
    return;
  }
  loading.value = true;
  if (currentContentId.value !== -1) {
    // 上报离开当前章节
    useApiReport.reportChapterRead(
      book.value.id,
      currentContentId.value,
      'exit',
    );
    heartBeat.stop();
  }
  // 获取章节内容
  const { data } = await useApiBooks.getBookChapterById(
    book.value.id,
    chapterId,
  );
  const rawContent = data || '';
  // 处理章节内容
  const processedContent = isHtml(rawContent)
    ? rawContent
    : rawContent
        .split('\n')
        .map((item) => `<p class='text-read-indent'>${item}</p>`)
        .join('');
  // 更新实际显示内容
  content.value = applySpacingToHtml(processedContent);
  // 更新当前内容ID
  currentContentId.value = chapterId;
  // 更新阅读历史
  updateReadingHistory(book.value.id, chapterId, currentContentIndex.value + 1);
  // 上报阅读数据,进入新章节
  useApiReport.reportChapterRead(book.value.id, chapterId, 'enter');
  heartBeat.start();
  // 等待DOM更新
  await nextTick();
  // 滚动到顶部
  bookReadContainer.value?.scrollTo({
    top: 0,
    behavior: 'instant',
  });
  loading.value = false;
};
// 在挂载前执行
onBeforeMount(async () => {
  try {
    // 从路由参数获取书籍ID和内容ID
    const bookId = parseInt(router.currentRoute.value.params.bookId as string);
    const contentId = parseInt(
      router.currentRoute.value.params.contentId as string,
    );
    book.value.id = bookId;
    if (contentId !== -1) {
      //获取书籍信息和目录
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const [rawBook, rawCatalog, _] = await Promise.all([
        bookStore.getBookById(bookId),
        bookStore.getCatalogById(bookId),
        run(contentId),
      ]);
      book.value = rawBook;
      catalog.value = rawCatalog.map((item, index) => ({
        ...item,
        title: `第${indexToCN(index + 1)}章 ${item.title}`,
      }));
    } else {
      //获取书籍信息和目录,然后获取第一个目录的内容
      const [rawBook, rawCatalog] = await Promise.all([
        bookStore.getBookById(bookId),
        bookStore.getCatalogById(bookId),
      ]);
      catalog.value = rawCatalog;
      book.value = rawBook;
      if (catalog.value.length > 0) {
        run(catalog.value[0].id);
      }
    }
  } catch (e) {
    console.log(e);
  }
});
// 在卸载前上报离开当前章节
onBeforeUnmount(() => {
  if (currentContentId.value !== -1) {
    useApiReport.reportChapterRead(
      book.value.id,
      currentContentId.value,
      'exit',
    );
  }
  heartBeat.stop();
});
</script>

<style scoped lang="css">
.book-read-container {
  margin: 0 auto;
  padding: 0 1rem 1rem 1rem;
  display: flex;
  justify-content: center;
}

.book-read-content {
  max-width: 700px;
}

.book-read-sidebar {
  position: fixed;
  top: 50%;
  left: calc(50vw + 450px);
  transform: translateY(-50%);
}

.book-read-catalog-container {
  min-width: 480px;
}

.book-read-catalog {
  max-height: calc(100vh - 4.5rem);
}

@media screen and (max-width: 768px) {
  .book-read-container {
    max-width: unset;
    width: 100%;
  }

  .book-read-content {
    max-width: unset;
    width: 100%;
  }

  .book-read-catalog-container {
    width: 70vw;
  }
}
</style>

// react_user/src/views/book/BookRead.tsx
import { useEffect, useRef, useState, useMemo, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Drawer, Spin } from 'antd';
import {
  UpOutlined,
  DownOutlined,
  UnorderedListOutlined,
  SettingOutlined,
  BookOutlined,
  FullscreenOutlined,
  SwapOutlined,
} from '@ant-design/icons';
import type { Book, Catalog } from '@guga-reading/types';
import {
  applySpacingToHtml,
  indexToCN,
  isHtml,
  useTitle,
  useApiBooks,
  useApiReport,
} from '@guga-reading/shares';
import { useBookStore, useReadSettingStore, useReadingHistoryStore } from '@/store';
import { useFullScreen } from '@/hooks';
import ReadSetting from '@/components/ReadSetting';

export default function BookRead() {
  const { bookId, contentId } = useParams<{
    bookId: string;
    contentId: string;
  }>();
  const navigate = useNavigate();
  const bookStore = useBookStore();
  const readingHistoryStore = useReadingHistoryStore();
  const useReadingSetting = useReadSettingStore();
  const fullScreen = useFullScreen();

  const containerRef = useRef<HTMLDivElement>(null);
  const [book, setBook] = useState<Book>({} as Book);
  const [catalog, setCatalog] = useState<Catalog[]>([]);
  const [content, setContent] = useState('');
  const [currentContentId, setCurrentContentId] = useState(-1);
  const [loading, setLoading] = useState(true);
  const [showCatalog, setShowCatalog] = useState(false);
  const [showReadSettings, setShowReadSettings] = useState(false);
  const [catalogAscOrder, setCatalogAscOrder] = useState(true);
  const [showBottomSettings, setShowBottomSettings] = useState(false);
  const [isLessThan768, setIsLessThan768] = useState(window.innerWidth < 768);

  useEffect(() => {
    const handler = () => setIsLessThan768(window.innerWidth < 768);
    window.addEventListener('resize', handler);
    return () => window.removeEventListener('resize', handler);
  }, []);

  const currentContentIndex = useMemo(
    () => catalog.findIndex((item) => item.id === currentContentId),
    [catalog, currentContentId],
  );

  const computeCatalog = useMemo(() => {
    if (catalogAscOrder) return catalog;
    return [...catalog].reverse();
  }, [catalog, catalogAscOrder]);

  // Heartbeat timer
  const heartBeatRef = useRef<number>(-1);

  const startHeartBeat = useCallback(
    (bId: number, chId: number) => {
      stopHeartBeat();
      heartBeatRef.current = window.setInterval(() => {
        if (chId !== -1) {
          useApiReport.reportChapterRead(bId, chId, 'heartbeat');
        }
      }, 10000);
    },
    [],
  );

  const stopHeartBeat = () => {
    if (heartBeatRef.current !== -1) {
      clearInterval(heartBeatRef.current);
      heartBeatRef.current = -1;
    }
  };

  const run = async (chapterId: number) => {
    if (currentContentId === chapterId) return;
    setLoading(true);

    if (currentContentId !== -1) {
      useApiReport.reportChapterRead(book.id, currentContentId, 'exit');
      stopHeartBeat();
    }

    const { data } = await useApiBooks.getBookChapterById(
      book.id,
      chapterId,
    );
    const rawContent = data || '';
    const processedContent = isHtml(rawContent)
      ? rawContent
      : rawContent
          .split('\n')
          .map((item) => `<p class='text-read-indent'>${item}</p>`)
          .join('');

    setContent(applySpacingToHtml(processedContent));
    setCurrentContentId(chapterId);

    // Update reading history
    readingHistoryStore.update(book.id, chapterId, currentContentIndex + 1);
    useApiReport.reportChapterRead(book.id, chapterId, 'enter');
    startHeartBeat(book.id, chapterId);

    setTimeout(() => {
      containerRef.current?.scrollTo({ top: 0, behavior: 'instant' });
      setLoading(false);
    }, 0);
  };

  useEffect(() => {
    useTitle(catalog[currentContentIndex]?.title || '');
  }, [currentContentIndex]);

  useEffect(() => {
    if (catalog.length > 0) {
      useTitle(catalog[currentContentIndex]?.title || '');
    }
  }, [catalog]);

  useEffect(() => {
    return () => {
      if (currentContentId !== -1) {
        useApiReport.reportChapterRead(book.id, currentContentId, 'exit');
      }
      stopHeartBeat();
    };
  }, []);

  useEffect(() => {
    if (bookId && contentId) {
      const bId = parseInt(bookId);
      const cId = parseInt(contentId);
      setBook((prev) => ({ ...prev, id: bId }));
      useApiBooks.getBookById(bId).then((rawBook) => {
        if (rawBook.success && rawBook.data) setBook(rawBook.data);
      });
      useApiBooks.getCatalogById(bId).then((rawCatalog) => {
        if (rawCatalog.success && rawCatalog.data) {
          const mapped = rawCatalog.data.map((item, index) => ({
            ...item,
            title: `第${indexToCN(index + 1)}章 ${item.title}`,
          }));
          setCatalog(mapped);
          run(cId);
        }
      });
    }
  }, [bookId, contentId]);

  const prevChapter = () => {
    if (currentContentIndex > 0) {
      navigate(
        `/book-read/${book.id}/${computeCatalog[currentContentIndex - 1].id}`,
        { replace: true },
      );
    }
  };

  const nextChapter = () => {
    if (currentContentIndex < computeCatalog.length - 1) {
      navigate(
        `/book-read/${book.id}/${computeCatalog[currentContentIndex + 1].id}`,
        { replace: true },
      );
    }
  };

  const contentStyle: React.CSSProperties = {
    backgroundColor: useReadingSetting.readSettings.backgroundColor,
    color: useReadingSetting.readSettings.color,
    fontSize: `${useReadingSetting.readSettings.fontSize}px`,
    fontFamily: useReadingSetting.readSettings.fontFamily,
    lineHeight: `${useReadingSetting.readSettings.lineHeight}px`,
    letterSpacing: `${useReadingSetting.readSettings.letterSpacing}px`,
  };

  return (
    <div
      ref={containerRef}
      style={{
        width: '100%',
        height: '100vh',
        overflow: 'auto',
      }}
    >
      <div
        className="book-read-container"
        style={{
          margin: '0 auto',
          display: 'flex',
          justifyContent: 'center',
          ...contentStyle,
        }}
      >
        {loading ? (
          <div style={{ height: '100vh', width: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
            <Spin size="large" />
          </div>
        ) : (
          <div
            className="book-read-content"
            style={{
              maxWidth: 700,
              width: '100%',
              padding: '0 1rem',
            }}
            onClick={() => {
              if (isLessThan768) setShowBottomSettings(true);
            }}
            dangerouslySetInnerHTML={{ __html: content }}
          />
        )}

        {/* Desktop sidebar */}
        {!isLessThan768 && (
          <div
            className="bg-card"
            style={{
              position: 'fixed',
              top: '50%',
              left: 'calc(50vw + 450px)',
              transform: 'translateY(-50%)',
              display: 'flex',
              flexDirection: 'column',
              gap: '0.5rem',
              padding: '0.5rem',
              borderRadius: '0.5rem',
              boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
            }}
          >
            <SidebarItem icon={<UpOutlined />} label="上一章" onClick={prevChapter} />
            <SidebarItem icon={<DownOutlined />} label="下一章" onClick={nextChapter} />
            <SidebarItem
              icon={<UnorderedListOutlined />}
              label="目录"
              onClick={() => setShowCatalog(true)}
            />
            <SidebarItem
              icon={<SettingOutlined />}
              label="阅读设置"
              onClick={() => setShowReadSettings(true)}
            />
            <SidebarItem
              icon={<BookOutlined />}
              label="书籍详情"
              onClick={() => navigate(`/book-detail/${book.id}`)}
            />
            <SidebarItem icon={<FullscreenOutlined />} label="全屏" onClick={fullScreen} />
          </div>
        )}
      </div>

      {/* Catalog Drawer */}
      <Drawer
        title={
          <div>
            <h3 style={{ margin: 0 }}>{book.name}</h3>
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                cursor: 'pointer',
              }}
              onClick={() => setCatalogAscOrder(!catalogAscOrder)}
            >
              <span>目录</span>
              <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                {catalogAscOrder ? '升序' : '降序'}
                <SwapOutlined
                  style={{
                    transform: `rotateZ(90deg) rotateY(${catalogAscOrder ? 0 : 180}deg)`,
                  }}
                />
              </span>
            </div>
          </div>
        }
        placement="left"
        open={showCatalog}
        onClose={() => setShowCatalog(false)}
        width={isLessThan768 ? '70vw' : 480}
      >
        <div style={{ maxHeight: 'calc(100vh - 4.5rem)', overflow: 'auto' }}>
          {computeCatalog.map((item) => (
            <p
              key={item.id}
              onClick={() => {
                navigate(`/book-read/${book.id}/${item.id}`, { replace: true });
                setShowCatalog(false);
              }}
              style={{
                cursor: 'pointer',
                padding: '0.25rem 0.5rem',
                margin: 0,
                borderRadius: '0.3rem',
                background:
                  item.id === currentContentId
                    ? 'var(--primary-color, #6366f1)'
                    : undefined,
                color: item.id === currentContentId ? '#fff' : undefined,
              }}
              className="bg-hover-secondary"
            >
              {item.title}
            </p>
          ))}
        </div>
      </Drawer>

      {/* Mobile Bottom Settings Drawer */}
      <Drawer
        placement="bottom"
        open={showBottomSettings && isLessThan768}
        onClose={() => setShowBottomSettings(false)}
        height="auto"
      >
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-evenly',
            flexWrap: 'wrap',
            gap: '1rem',
            padding: '0.5rem',
          }}
          onClick={() => setShowBottomSettings(false)}
        >
          <BottomItem icon={<UpOutlined />} label="上一章" onClick={prevChapter} />
          <BottomItem icon={<DownOutlined />} label="下一章" onClick={nextChapter} />
          <BottomItem
            icon={<UnorderedListOutlined />}
            label="目录"
            onClick={() => setShowCatalog(true)}
          />
          <BottomItem
            icon={<SettingOutlined />}
            label="阅读设置"
            onClick={() => setShowReadSettings(true)}
          />
          <BottomItem
            icon={<BookOutlined />}
            label="书籍详情"
            onClick={() => navigate(`/book-detail/${book.id}`)}
          />
          <BottomItem icon={<FullscreenOutlined />} label="全屏" onClick={fullScreen} />
        </div>
      </Drawer>

      {/* Read Settings Drawer */}
      <Drawer
        title="阅读设置"
        placement="left"
        open={showReadSettings}
        onClose={() => setShowReadSettings(false)}
      >
        <ReadSetting />
      </Drawer>
    </div>
  );
}

function SidebarItem({
  icon,
  label,
  onClick,
}: {
  icon: React.ReactNode;
  label: string;
  onClick: () => void;
}) {
  return (
    <div
      onClick={onClick}
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        cursor: 'pointer',
        padding: '0.5rem',
        borderRadius: '0.3rem',
      }}
      className="bg-hover-secondary"
    >
      <span style={{ fontSize: '24px' }}>{icon}</span>
      <span style={{ fontSize: '0.8rem' }}>{label}</span>
    </div>
  );
}

function BottomItem({
  icon,
  label,
  onClick,
}: {
  icon: React.ReactNode;
  label: string;
  onClick: () => void;
}) {
  return (
    <div
      onClick={onClick}
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        cursor: 'pointer',
      }}
    >
      <span style={{ fontSize: '24px' }}>{icon}</span>
      <span style={{ fontSize: '0.8rem' }}>{label}</span>
    </div>
  );
}
