// user/src/views/book/BookShelf.vue
<template>
  <div class="container-column">
    <div class="inner-container hidden-768">
      <q-form-button @click="showClose = !showClose"> 批量管理 </q-form-button>
    </div>
    <div class="shelf-container">
      <QSwiperAction
        v-for="histortItem in shelfStore.getBookShelf"
        :key="histortItem.id"
        :disabled="!isLessThan768"
        :threshold="30"
      >
        <div class="bg-card container">
          <div
            class="inner-close"
            v-show="showClose && !isLessThan768"
            @click="shelfStore.delete(histortItem.id)"
          >
            <q-icon icon="Close" size="16px" />
          </div>
          <QLazyImage
            :src="histortItem.cover"
            :height="height"
            :width="width"
          />
          <div class="container-flex-1 inner-container-column">
            <h5 class="text-one-line">{{ histortItem.name }}</h5>
            <div class="inner-container">
              <QIcon icon="User" size="14px"></QIcon>
              <span class="text-08rem">{{ histortItem.author }}</span>
            </div>
            <div class="inner-container" v-if="histortItem.last_read_at">
              <QIcon icon="History" size="14px"></QIcon>
              <p>
                <span class="text-08rem">上次阅读:</span>
                <span class="text-08rem">{{
                  histortItem.last_read_at?.split('T')[0]
                }}</span>
              </p>
            </div>
            <div>
              <QFormButton
                type="button"
                @click="
                  () =>
                    router.push(
                      `/book-read/${histortItem.id}/${histortItem.last_chapter_id}`,
                    )
                "
              >
                <span> 继续阅读 </span>
              </QFormButton>
            </div>
          </div>
        </div>
        <template #action>
          <div
            class="padding-46rem container-center container-h100 delete-768"
            @click="shelfStore.delete(histortItem.id)"
          >
            删除
          </div>
        </template>
      </QSwiperAction>
    </div>
  </div>
</template>
<script setup lang="ts">
import { onBeforeMount, ref } from 'vue';
import router from '@/route';
import { useBookShelfStore } from '@/store';
import { useWindowResize } from 'qyani-components';
import {
  QSwiperAction,
  QIcon,
  QFormButton,
  QLazyImage,
} from 'qyani-components';
const width = ref(96);
const height = ref(144);
const isLessThan768 = ref(window.innerWidth < 768);
const showClose = ref(false);
useWindowResize.addHandler((width) => {
  isLessThan768.value = width < 768;
});
const shelfStore = useBookShelfStore();
onBeforeMount(async () => {
  shelfStore.get();
});
</script>
<style scoped lang="css">
.shelf-container {
  width: 100%;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  grid-auto-rows: auto;
  gap: 0.5rem;
  padding: 0.25rem;
}
</style>

// react_user/src/views/book/BookShelf.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button, Image, Tag } from 'antd';
import { CloseOutlined, UserOutlined, HistoryOutlined } from '@ant-design/icons';
import { useBookShelfStore } from '@/store';

export default function BookShelf() {
  const navigate = useNavigate();
  const shelfStore = useBookShelfStore();
  const [showClose, setShowClose] = useState(false);
  const [isLessThan768, setIsLessThan768] = useState(window.innerWidth < 768);

  const width = 96;
  const height = 144;

  useEffect(() => {
    const handler = () => setIsLessThan768(window.innerWidth < 768);
    window.addEventListener('resize', handler);
    return () => window.removeEventListener('resize', handler);
  }, []);

  useEffect(() => {
    shelfStore.get();
  }, []);

  return (
    <div className="container-column">
      {!isLessThan768 && (
        <div style={{ padding: '0.5rem' }}>
          <Button onClick={() => setShowClose(!showClose)}>
            批量管理
          </Button>
        </div>
      )}

      <div
        style={{
          width: '100%',
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
          gap: '0.5rem',
          padding: '0.25rem',
        }}
      >
        {shelfStore.getBookShelf().map((item) => (
          <div
            key={item.id}
            className="bg-card"
            style={{
              display: 'flex',
              gap: '0.5rem',
              padding: '0.5rem',
              borderRadius: '0.5rem',
              position: 'relative',
            }}
          >
            {/* Close button for desktop batch mode */}
            {showClose && !isLessThan768 && (
              <div
                className="inner-close"
                onClick={() => shelfStore.delete(item.id)}
                style={{ cursor: 'pointer' }}
              >
                <CloseOutlined />
              </div>
            )}

            <Image
              src={item.cover}
              height={height}
              width={width}
              preview={false}
              fallback="/figure.webp"
              style={{ objectFit: 'cover' }}
            />

            <div
              style={{
                flex: 1,
                display: 'flex',
                flexDirection: 'column',
                gap: '0.25rem',
              }}
            >
              <h5 style={{ margin: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {item.name}
              </h5>

              <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                <UserOutlined style={{ fontSize: '14px' }} />
                <span style={{ fontSize: '0.8rem' }}>{item.author}</span>
              </div>

              {item.lastReadAt && (
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                  <HistoryOutlined style={{ fontSize: '14px' }} />
                  <span style={{ fontSize: '0.8rem' }}>
                    上次阅读: {item.lastReadAt.split('T')[0]}
                  </span>
                </div>
              )}

              <div>
                <Button
                  type="primary"
                  size="small"
                  onClick={() =>
                    navigate(
                      `/book-read/${item.id}/${item.lastChapterId}`,
                    )
                  }
                >
                  继续阅读
                </Button>
              </div>

              {/* Mobile delete button */}
              {isLessThan768 && (
                <div
                  className="delete-768"
                  onClick={() => shelfStore.delete(item.id)}
                  style={{
                    padding: '0.5rem',
                    textAlign: 'center',
                    borderRadius: '0.3rem',
                    cursor: 'pointer',
                  }}
                >
                  删除
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
